export enum ExecutionState {
  SIGNAL_CREATED = 'SIGNAL_CREATED',
  SIGNAL_VALIDATED = 'SIGNAL_VALIDATED',
  ROUTED = 'ROUTED',
  RISK_CHECKED = 'RISK_CHECKED',
  CONFLICT_RESOLVED = 'CONFLICT_RESOLVED',
  SCHEDULED = 'SCHEDULED',
  DISPATCHED = 'DISPATCHED',
  ORDER_SENT = 'ORDER_SENT',
  ORDER_ACKED = 'ORDER_ACKED',
  ORDER_REJECTED = 'ORDER_REJECTED',
  POSITION_OPENED = 'POSITION_OPENED',
  POSITION_CLOSED = 'POSITION_CLOSED',
  PNL_REALIZED = 'PNL_REALIZED',
  POST_ANALYSIS_DONE = 'POST_ANALYSIS_DONE',
  CANCELLED = 'CANCELLED',
  TIMEOUT = 'TIMEOUT',
  FAILED_HARD = 'FAILED_HARD',
}

export const TERMINAL_STATES: ExecutionState[] = [
  ExecutionState.POST_ANALYSIS_DONE,
  ExecutionState.CANCELLED,
  ExecutionState.TIMEOUT,
  ExecutionState.FAILED_HARD,
];

export const ERROR_STATES: ExecutionState[] = [
  ExecutionState.ORDER_REJECTED,
  ExecutionState.CANCELLED,
  ExecutionState.TIMEOUT,
  ExecutionState.FAILED_HARD,
];
